server:
  port: 8080
  servlet:
    context-path: /v0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: wx_app_github
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:


github:
  api:
    token: 'myToken'
